on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
    - uses: actions/checkout@v3
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: rvgl.flatpak
        manifest-path: org.rvgl.rvmm.yml
  deploy:
    needs: flatpak
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: rvgl-x86_64

    - uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: rvgl.flatpak
        tag_name: latest
        overwrite: true
        update_latest_release: true
        draft: false
    - uses: rickstaa/action-create-tag@v1
      with:
        tag: latest
        force_push_tag: true
