name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  repository_dispatch:

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/andyholmes/flatter/freedesktop:23.08
      options: --privileged

    steps:
    - uses: actions/checkout@v4

    - uses: andyholmes/flatter@main
      with:
        files: org.rvgl.rvmm.yml
        upload-bundles: true
        upload-pages-artifact: true
        upload-pages-includes: |
          rvgl.flatpakref

  deploy:
    name: Deploy
    if: ${{ github.ref == 'refs/heads/main' }}

    needs: flatpak
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

  release:
    name: Release
    if: ${{ github.ref == 'refs/heads/main' }}

    needs: flatpak
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: org.rvgl.rvmm-x86_64

    - run: |
        mv org.rvgl.rvmm.flatpak rvgl.flatpak

    - uses: rickstaa/action-create-tag@v1
      with:
        tag: latest
        force_push_tag: true

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        fail_on_unmatched_files: true
        files: |
          rvgl.flatpak
